apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: k8s-python-framework
build:
  artifacts:
    - image: k8s-python-framework
      docker:
         dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
deploy:
   kustomize:
     paths: ["kustomize/overlays/dev"]
